# Generated by Django 5.1.1 on 2024-10-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemperatureMeasurement',
            new_name='Measurement',
        ),
    ]
